# Generated by Django 3.0.6 on 2020-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='celular',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
