# Generated by Django 3.0.6 on 2020-05-23 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0002_miembro_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='fm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='uc',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='um',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
