# Generated by Django 3.0.6 on 2020-05-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0003_auto_20200523_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('uc', models.IntegerField(blank=True, editable=False, null=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('descripcion', models.CharField(help_text='Descripción del género', max_length=45, unique=True, verbose_name='Descripción género')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.AlterModelOptions(
            name='miembro',
            options={'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
        migrations.AddField(
            model_name='miembro',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=70, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='genero',
            field=models.ForeignKey(default=1, help_text='Gérero del beneficiario', on_delete=django.db.models.deletion.PROTECT, to='miembro.Genero', verbose_name='Género'),
            preserve_default=False,
        ),
    ]
