# Generated by Django 3.0.6 on 2020-05-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0009_barrio_rol_miembro_sede_tipo_sangre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_sangre',
            options={'verbose_name': 'Tipo_sangre', 'verbose_name_plural': 'Tipo_sangre'},
        ),
        migrations.AddField(
            model_name='miembro',
            name='barrio',
            field=models.ForeignKey(help_text='Barrio donde vive el miembro', null=True, on_delete=django.db.models.deletion.PROTECT, to='miembro.Barrio', verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='eps',
            field=models.ForeignKey(help_text='EPS del miembro', null=True, on_delete=django.db.models.deletion.PROTECT, to='miembro.Eps', verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='rol_miembro',
            field=models.ForeignKey(help_text='Roldel miembro dentro de la rama', null=True, on_delete=django.db.models.deletion.PROTECT, to='miembro.Rol_miembro', verbose_name='Rol miembro'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='sede',
            field=models.ForeignKey(help_text='Sede donde estudia el miembro', null=True, on_delete=django.db.models.deletion.PROTECT, to='miembro.Sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='tipo_sangre',
            field=models.ForeignKey(help_text='Tipo de sangre del miembro', null=True, on_delete=django.db.models.deletion.PROTECT, to='miembro.Tipo_sangre', verbose_name='RH'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='genero',
            field=models.ForeignKey(help_text='Gérero del miembro', null=True, on_delete=django.db.models.deletion.PROTECT, to='miembro.Genero', verbose_name='Género'),
        ),
    ]
