# Generated by Django 3.0.6 on 2020-05-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0011_auto_20200524_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la sede dende estudia', max_length=255, unique=True, verbose_name='Descripción sede'),
        ),
    ]
